# -*- coding: utf-8 -*-
"""Trabalho Ciência de Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157FUAleo7q_7XEtIE2-dN-vrmhTAGTI0
"""

# ETL
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Análise dos dados
import matplotlib
import matplotlib.gridspec as gridspec
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Modelagem Preditiva
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier, plot_tree

# %matplotlib inline

# Machine Learning
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN

# Métricas de Avaliação de Modelos
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

from google.colab import drive
drive.mount('/content/drive')

df_amazon_sales = pd.read_csv('/content/drive/MyDrive/Dataset ciência de dados/amazon.csv')

df_amazon_sales.head()

df_amazon_sales.info()

"""# Tratamento dos Dados"""

df_amazon_sales.isna().sum()

df_amazon_sales[df_amazon_sales.isna().any(axis=1)]

df_amazon_sales['rating_count'] = df_amazon_sales['rating_count'].astype('string')

df_amazon_sales['rating_count'] = df_amazon_sales['rating_count'].str.replace(',', '')

df_amazon_sales = df_amazon_sales.dropna(subset=['rating_count'])

df_amazon_sales.isna().sum()

df_amazon_sales[df_amazon_sales.isna().any(axis=1)]

df_amazon_sales['rating_count'] = df_amazon_sales['rating_count'].astype('int64')

df_amazon_sales[['product_id', 'product_name']] = df_amazon_sales[['product_id', 'product_name']].astype('string')

df_amazon_sales = df_amazon_sales.drop(columns=['img_link', 'product_link'])

df_amazon_sales[['discounted_price', 'actual_price']] = df_amazon_sales[['discounted_price', 'actual_price']].astype('string')

df_amazon_sales[['discounted_price', 'actual_price']] = (
    df_amazon_sales[['discounted_price', 'actual_price']]
    .apply(lambda col: col.astype('string')
           .str.replace(',', '', regex=False)
           .str.replace('₹', '', regex=False))
)

df_amazon_sales[['discounted_price', 'actual_price']] = df_amazon_sales[['discounted_price', 'actual_price']].astype('float64')
df_amazon_sales[['discounted_price', 'actual_price']] *= 0.057 # Conversão de rúpias para reais (aproximado)
df_amazon_sales[['discounted_price', 'actual_price']] = df_amazon_sales[['discounted_price', 'actual_price']].round(2)

df_amazon_sales.loc[
    pd.to_numeric(df_amazon_sales['rating'], errors='coerce').isna(),
    'rating'
].value_counts(dropna=False)

df_amazon_sales['rating'] = (
    df_amazon_sales['rating']
    .astype('string')
    .str.replace('|', '', regex=False)
    .pipe(pd.to_numeric, errors='coerce')
)

df_amazon_sales['category'] = df_amazon_sales['category'].astype('string')

df_amazon_sales['category'] = df_amazon_sales['category'].apply(lambda x: x.split('|'))

df_amazon_sales['discount_percentage'] = df_amazon_sales['discount_percentage'].astype('string')
df_amazon_sales['discount_percentage'] = df_amazon_sales['discount_percentage'].str.replace('%', '', regex=False)
df_amazon_sales['discount_percentage'] = df_amazon_sales['discount_percentage'].astype('int64')

df_amazon_sales['about_product'] = df_amazon_sales['about_product'].astype('string')

df_amazon_sales['user_id'] = df_amazon_sales['user_id'].str.split(',')
df_amazon_sales['user_name'] = df_amazon_sales['user_name'].str.split(',')
df_amazon_sales['review_id'] = df_amazon_sales['review_id'].str.split(',')
df_amazon_sales['review_title'] = df_amazon_sales['review_title'].str.split(',')
df_amazon_sales['review_content'] = df_amazon_sales['review_content'].str.split(',')
df_amazon_sales.info()

df_amazon_sales[df_amazon_sales.duplicated(subset=['product_id'])]

df_amazon_sales = df_amazon_sales.drop_duplicates(subset=['product_id']).reset_index(drop=True)

df_amazon_sales

df_amazon_sales['rating'].isna().sum()

df_amazon_sales = df_amazon_sales.dropna(subset=['rating'])

df_amazon_sales['rating'].isna().sum()

df_amazon_sales.info()

df_amazon_sales.head()

"""# Análise de Dados (KPIs)"""

df_amazon_sales.describe()

print("Moda dos preços com desconto: ", df_amazon_sales['discounted_price'].mode()[0])
print("Moda dos preços: ", df_amazon_sales['actual_price'].mode()[0])
print("Moda dos descontos: ", df_amazon_sales['discount_percentage'].mode()[0])
print("Moda das avaliações: ", df_amazon_sales['rating'].mode()[0])
print("Moda da quantida de avaliações: ", df_amazon_sales['rating_count'].mode()[0])

df_amazon_sales.sort_values(by='actual_price', ascending=False).head(10)
# 10 produtos mais caros

df_amazon_sales.sort_values(by='actual_price', ascending=True).head(10)
# 10 produtos mais baratos

df_amazon_sales.sort_values(by='rating', ascending=False).head(10)
# 10 produtos com maiores avaliações

df_amazon_sales.sort_values(by='rating', ascending = True).head(10)
# 10 produtos com menores avaliações

df_amazon_sales.sort_values(by='rating_count', ascending=False).head(10)
# 10 produtos com mais avaliações

plt.scatter(df_amazon_sales['actual_price'], df_amazon_sales['rating'])
plt.title("Distribuição de Avaliações por Preço")
plt.xlabel("Preço")
plt.ylabel("Avaliação")
plt.show()

df_amazon_sales = df_amazon_sales.copy()

df_amazon_sales['faixa_preco'] = pd.cut(
    df_amazon_sales['actual_price'],
    bins=[0,50,100,200,500,1000,5000]
)

df_preco_rating = (
    df_amazon_sales
    .groupby('faixa_preco', observed=False)['rating']
    .agg('mean')
    .round(2)
)

df_preco_rating

plt.scatter(df_amazon_sales['discount_percentage'], df_amazon_sales['rating'])
plt.title("Distribuição de Avaliações por Desconto")
plt.xlabel("Porcentagem de Desconto")
plt.ylabel("Avaliação")
plt.show()

df_amazon_sales.loc[:, 'faixa_desconto'] = pd.cut(
    df_amazon_sales['discount_percentage'],
    bins=[0,10,20,30,40,50,100]
)

df_amazon_sales.groupby('faixa_desconto', observed=False)['rating'].mean().round(2)

plt.hist(df_amazon_sales['rating'], bins=20)
plt.title("Distribuição de Avaliações")
plt.xlabel("Avaliação")
plt.ylabel("Quantidade")
plt.show()

df_amazon_sales['rating'].value_counts().sort_index()
# Quantidade de Avaliações por Nota

plt.hist(df_amazon_sales['actual_price'], bins=50)
plt.title("Distribuição de Preço")
plt.xlabel("Preço")
plt.ylabel("Quantidade")
plt.show()

df_amazon_sales['faixa_preco'] = pd.cut(
    df_amazon_sales['actual_price'],
    bins=[0,50,100,200,500,1000,5000,10000]
)

df_amazon_sales.groupby(
    'faixa_preco',
    observed=False
)['actual_price'].count()

# Quantidade de Produtos por Faixa de Preço

df_cat = df_amazon_sales.explode('category')
df_cat['category'].value_counts().head(10)
# Quantidade de Produtos por Categoria

df_media_preco_categoria = df_cat.groupby('category')['actual_price'].mean().round(2)
df_media_preco_categoria
# Preço médio po categoria

df_media_avaliacao_categoria = df_cat.groupby('category')['rating'].mean().round(2)
df_media_avaliacao_categoria
# Preço médio po categoria

df_avaliacao_categoria = df_cat.groupby('category')['rating'].count()
df_avaliacao_categoria
# Quantidade de avaliações por categoria

df_amazon_sales.sort_values(by='discount_percentage', ascending=False).head(10)
# Produtos com maior porcentagem de desconto

df_amazon_sales.sort_values(by='discount_percentage', ascending=True).head(10)
# Produtos com menor porcentagem de desconto

"""# Exportação do DataFrame Tratado"""

df_amazon_sales.to_csv('amazon_sales_clean.csv', index=False)
# Arquivo .csv tratado

df_amazon_sales.to_excel("amazon_sales.xlsx", index=False)
# Arquivo excel tratado

df_media_preco_categoria.to_excel("media_preco_categoria.xlsx")
# Arquivo excel com média de preço por categoria

df_media_avaliacao_categoria.to_excel("media_avaliacao_categoria.xlsx")
# Arquivo excel com média de avaliação por categoria

df_avaliacao_categoria.to_excel("avaliacao_categoria.xlsx")
# Arquivo excel com quantidade de avaliações por categoria

"""# Modelagem Preditiva, Algoritmos de Machine Learning e Métricas de Avaliação de Modelos"""

X = df_amazon_sales[['actual_price', 'discount_percentage']].dropna()
y = df_amazon_sales.loc[X.index, 'rating']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

modelo_lr = LinearRegression()
modelo_lr.fit(X_train, y_train)
y_pred = modelo_lr.predict(X_test)

print(f"R²:   {r2_score(y_test, y_pred):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):.4f}")
print(f"Coeficientes → actual_price: {modelo_lr.coef_[0]:.6f} | discount_percentage: {modelo_lr.coef_[1]:.6f}")
print(f"Intercepto: {modelo_lr.intercept_:.4f}")

plt.figure(figsize=(8, 5))
plt.scatter(y_test, y_pred, alpha=0.4, color='steelblue', label='Predições')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', label='Ideal')
plt.xlabel("Rating Real")
plt.ylabel("Rating Previsto")
plt.title("Regressão Linear — Rating Real vs Previsto (Amazon)")
plt.legend()
plt.tight_layout()
plt.show()

# Criar variável binária: 1 se rating >= 4, 0 caso contrário
df_log = df_amazon_sales[['actual_price', 'discount_percentage', 'rating_count', 'rating']].dropna().copy()
df_log['bom_produto'] = (df_log['rating'] >= 4).astype(int)

X_log = df_log[['actual_price', 'discount_percentage', 'rating_count']]
y_log = df_log['bom_produto']

scaler = StandardScaler()
X_log_scaled = scaler.fit_transform(X_log)

X_train, X_test, y_train, y_test = train_test_split(X_log_scaled, y_log, test_size=0.2, random_state=42)

modelo_logit = LogisticRegression(max_iter=1000)
modelo_logit.fit(X_train, y_train)
y_pred_log = modelo_logit.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report
print(f"Acurácia: {accuracy_score(y_test, y_pred_log):.4f}")
print(classification_report(y_test, y_pred_log, target_names=['Rating < 4', 'Rating >= 4']))

df_kmeans = df_amazon_sales[['actual_price', 'discount_percentage', 'rating', 'rating_count']].dropna().copy()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_kmeans)

# Método do cotovelo para escolher K
inertias = []
k_range = range(2, 10)
for k in k_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_scaled)
    inertias.append(km.inertia_)

plt.figure(figsize=(8, 4))
plt.plot(k_range, inertias, marker='o', color='steelblue')
plt.xlabel("Número de Clusters (K)")
plt.ylabel("Inércia")
plt.title("Método do Cotovelo — K-Means Amazon")
plt.xticks(k_range)
plt.tight_layout()
plt.show()

# Aplicar com K=4
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df_kmeans['cluster'] = kmeans.fit_predict(X_scaled)

# Perfil de cada cluster
print(df_kmeans.groupby('cluster').agg(
    preco_medio=('actual_price', 'mean'),
    desconto_medio=('discount_percentage', 'mean'),
    rating_medio=('rating', 'mean'),
    n_reviews_medio=('rating_count', 'mean'),
    n_produtos=('rating', 'count')
).round(2))

# Scatter plot dos clusters
plt.figure(figsize=(9, 6))
sns.scatterplot(data=df_kmeans, x='actual_price', y='rating',
                hue='cluster', palette='tab10', alpha=0.6, s=50)
plt.title("K-Means — Clusters de Produtos Amazon")
plt.xlabel("Preço (R$)")
plt.ylabel("Rating")
plt.legend(title="Cluster")
plt.tight_layout()
plt.show()

df_db = df_amazon_sales[['actual_price', 'discount_percentage']].dropna().copy()
X_db = StandardScaler().fit_transform(df_db)

dbscan = DBSCAN(eps=0.5, min_samples=5)
df_db['cluster_db'] = dbscan.fit_predict(X_db)

n_clusters = len(set(df_db['cluster_db'])) - (1 if -1 in df_db['cluster_db'].values else 0)
n_outliers  = (df_db['cluster_db'] == -1).sum()
print(f"Clusters encontrados: {n_clusters}")
print(f"Outliers detectados:  {n_outliers}")

plt.figure(figsize=(9, 6))
sns.scatterplot(data=df_db, x='actual_price', y='discount_percentage',
                hue='cluster_db', palette='tab10', alpha=0.5, s=40)
plt.title("DBSCAN — Clusters e Outliers (Amazon)")
plt.xlabel("Preço (R$)")
plt.ylabel("Desconto (%)")
plt.legend(title="Cluster (-1 = outlier)")
plt.tight_layout()
plt.show()

cm = confusion_matrix(y_test, y_pred_log)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                               display_labels=['Rating < 4', 'Rating ≥ 4'])
fig, ax = plt.subplots(figsize=(6, 5))
disp.plot(ax=ax, colorbar=False, cmap='Blues')
plt.title("Matriz de Confusão — Regressão Logística (Amazon)")
plt.tight_layout()
plt.show()

"""#DataSets Brasileiros

##Tratamento de Dados
"""

df_br_products = pd.read_csv("/content/drive/MyDrive/Dataset ciência de dados/olist_products_dataset.csv")#
df_br_customers = pd.read_csv("/content/drive/MyDrive/Dataset ciência de dados/olist_customers_dataset.csv")#
df_br_location = pd.read_csv("/content/drive/MyDrive/Dataset ciência de dados/olist_geolocation_dataset.csv")#
df_br_payments = pd.read_csv("/content/drive/MyDrive/Dataset ciência de dados/olist_order_payments_dataset.csv")#
df_br_items = pd.read_csv("/content/drive/MyDrive/Dataset ciência de dados/olist_order_items_dataset.csv")#
df_br_reviews = pd.read_csv("/content/drive/MyDrive/Dataset ciência de dados/olist_order_reviews_dataset.csv")#
df_br_orders = pd.read_csv("/content/drive/MyDrive/Dataset ciência de dados/olist_orders_dataset.csv")#
df_br_sellers = pd.read_csv("/content/drive/MyDrive/Dataset ciência de dados/olist_sellers_dataset.csv")
df_br_category = pd.read_csv("/content/drive/MyDrive/Dataset ciência de dados/product_category_name_translation.csv")

df_br_products.info()

df_br_products.isna().sum()

df_br_products[df_br_products.isna().any(axis=1)]

df_br_products[df_br_products.duplicated(subset=['product_id'])]

df_br_products = df_br_products.dropna()

df_br_customers.info()

df_br_customers.isna().sum()

df_br_customers[df_br_customers.duplicated()]

df_br_location.isna().sum()

df_br_items.isna().sum()

df_br_items[df_br_items.duplicated()]

df_br_payments.isna().sum()

df_br_payments[df_br_payments.duplicated(subset=['order_id'])]

df_br_payments = df_br_payments.drop_duplicates(subset=['order_id']).reset_index(drop=True)

df_br_reviews.isna().sum()

df_br_reviews = df_br_reviews.drop(columns=['review_comment_title', 'review_comment_message'])

df_br_orders.isna().sum()

df_br_orders = df_br_orders.drop(columns=['order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date'])

df_br_sellers.isna().sum()

df_br_category.isna().sum()

# ── Tradução de categorias ──────────────────────────────────
df_br_products = df_br_products.merge(df_br_category, on='product_category_name', how='left')
df_br_products['category'] = df_br_products['product_category_name_english'].fillna(
    df_br_products['product_category_name'].fillna('unknown')
)

# ── Conversão de datas ──────────────────────────────────────
df_br_orders['order_purchase_timestamp'] = pd.to_datetime(
    df_br_orders['order_purchase_timestamp'], errors='coerce'
)
df_br_orders['order_estimated_delivery_date'] = pd.to_datetime(
    df_br_orders['order_estimated_delivery_date'], errors='coerce'
)

# ── Geolocalização sem duplicatas ───────────────────────────
df_br_location = df_br_location.drop_duplicates(subset=['geolocation_zip_code_prefix'])

# ── Merge principal: itens → pedidos → clientes → produtos → vendedores ──
base = (df_br_items
        .merge(df_br_orders[['order_id', 'customer_id', 'order_status',
                              'order_purchase_timestamp',
                              'order_estimated_delivery_date']],
               on='order_id', how='left')
        .merge(df_br_customers[['customer_id', 'customer_state', 'customer_city']],
               on='customer_id', how='left')
        .merge(df_br_products[['product_id', 'category']],
               on='product_id', how='left')
        .merge(df_br_sellers[['seller_id', 'seller_state']],
               on='seller_id', how='left')
)

# ── Review médio por pedido ─────────────────────────────────
review_agg = df_br_reviews.groupby('order_id')['review_score'].mean().reset_index()
base = base.merge(review_agg, on='order_id', how='left')

# ── Pagamento total por pedido → calcular desconto ──────────
pay_agg = (df_br_payments.groupby('order_id')['payment_value']
           .sum().reset_index().rename(columns={'payment_value': 'total_paid'}))
base = base.merge(pay_agg, on='order_id', how='left')

order_totals = base.groupby('order_id').agg(
    order_price=('price', 'sum'),
    order_freight=('freight_value', 'sum')
).reset_index()
order_totals['order_subtotal'] = order_totals['order_price'] + order_totals['order_freight']
base = base.merge(order_totals[['order_id', 'order_subtotal']], on='order_id', how='left')

base['discount_value'] = np.where(
    base['order_subtotal'] > 0,
    np.clip(
        (base['order_subtotal'] - base['total_paid'])
        * (base['price'] / base['order_subtotal'].replace(0, np.nan)),
        0, None
    ),
    0
)
base['discount_pct'] = np.where(
    base['price'] > 0,
    np.clip(base['discount_value'] / base['price'] * 100, 0, 100),
    0
)

# ── Base filtrada apenas com pedidos entregues ──────────────
base_delivered = base[base['order_status'] == 'delivered'].copy()

print(f"Base consolidada (all):       {base.shape}")
print(f"Base consolidada (delivered): {base_delivered.shape}")

"""# Análise de Dados (KPIs)"""

def style_ax(ax, title='', xlabel='', ylabel=''):
    ax.set_title(title, color='#ffffff', fontsize=13, fontweight='bold', pad=10)
    ax.set_xlabel(xlabel, color='#b0b0c0', fontsize=10)
    ax.set_ylabel(ylabel, color='#b0b0c0', fontsize=10)
    ax.tick_params(colors='#a0a0b0')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#2d3148')
    ax.spines['bottom'].set_color('#2d3148')
    ax.grid(True, axis='y', alpha=0.3, color='#2d3148')
    return ax

def add_bar_labels(ax, fmt='{:.0f}', color='#e0e0e0', fontsize=8.5, rotation=0):
    for p in ax.patches:
        h = p.get_height()
        if h > 0:
            ax.annotate(
                fmt.format(h),
                (p.get_x() + p.get_width() / 2., h),
                ha='center', va='bottom', fontsize=fontsize,
                color=color, rotation=rotation,
                xytext=(0, 3), textcoords='offset points'
            )

def section_banner(title):
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"{'='*60}")

# ── KPI 1 – Preço médio dos produtos ───────────────────────
avg_price = df_br_items['price'].mean()
print(f"[KPI 1] Preço médio dos produtos: R$ {avg_price:.2f}")

# ── KPI 2 – Preço médio por categoria ──────────────────────
avg_price_cat = (base_delivered.groupby('category')['price']
                 .mean()
                 .sort_values(ascending=False)
                 .reset_index()
                 .rename(columns={'price': 'avg_price'}))
print(f"\n[KPI 2] Preço médio por categoria (top 10):")
print(avg_price_cat.head(10).to_string(index=False))

# ── KPI 3 – Preço máximo ────────────────────────────────────
max_price = df_br_items['price'].max()
print(f"\n[KPI 3] Preço máximo: R$ {max_price:.2f}")

# ── KPI 4 – Preço mínimo + desvio padrão ───────────────────
min_price = df_br_items['price'].min()
std_price  = df_br_items['price'].std()
print(f"[KPI 4] Preço mínimo: R$ {min_price:.2f}")
print(f"[KPI 4] Desvio padrão de preços: R$ {std_price:.2f}")

# ── KPI 5 – Percentual médio de desconto ────────────────────
avg_disc_pct = base_delivered['discount_pct'].mean()
print(f"\n[KPI 5] Percentual médio de desconto: {avg_disc_pct:.2f}%")

# ── KPI 6 – Valor médio de desconto ─────────────────────────
avg_disc_val = base_delivered['discount_value'].mean()
print(f"[KPI 6] Valor médio de desconto: R$ {avg_disc_val:.2f}")

# ── KPI 7 – Produtos com maior desconto (top 10) ────────────
prod_discount = (base_delivered.groupby('product_id')
                 .agg(avg_discount_pct=('discount_pct', 'mean'),
                      avg_price=('price', 'mean'),
                      n_vendas=('order_id', 'count'))
                 .reset_index()
                 .sort_values('avg_discount_pct', ascending=False))

print(f"\n[KPI 7] Top 10 produtos com maior desconto:")
print(prod_discount.head(10)[['product_id', 'avg_discount_pct', 'avg_price', 'n_vendas']].to_string(index=False))

# ── KPI 8 – Produtos com menor desconto (excluindo zero) ────
prod_discount_sem_zero = prod_discount[prod_discount['avg_discount_pct'] > 0]
print(f"\n[KPI 8] Top 10 produtos com menor desconto (> 0%):")
print(prod_discount_sem_zero.tail(10)[['product_id', 'avg_discount_pct', 'avg_price']].to_string(index=False))

# ── KPI 9 – Rating médio dos produtos ───────────────────────
avg_rating = base_delivered['review_score'].mean()
print(f"[KPI 9]  Rating médio dos produtos: {avg_rating:.2f} ⭐")

# ── KPI 10 – Rating médio por categoria (mín. 50 reviews) ───
avg_rating_cat = (base_delivered.groupby('category')['review_score']
                  .agg(['mean', 'count'])
                  .reset_index()
                  .rename(columns={'mean': 'avg_rating', 'count': 'n_reviews'})
                  .query('n_reviews >= 50')
                  .sort_values('avg_rating', ascending=False))
print(f"\n[KPI 10] Rating médio por categoria (top 10):")
print(avg_rating_cat.head(10).to_string(index=False))

# ── KPI 11 – Produtos com maior rating (mín. 10 reviews) ────
prod_rating = (base_delivered.groupby('product_id')['review_score']
               .agg(['mean', 'count'])
               .reset_index()
               .rename(columns={'mean': 'avg_rating', 'count': 'n_reviews'})
               .query('n_reviews >= 10')
               .sort_values('avg_rating', ascending=False))
print(f"\n[KPI 11] Top 10 produtos com maior rating:")
print(prod_rating.head(10).to_string(index=False))

# ── KPI 12 – Produtos com menor rating (mín. 10 reviews) ────
print(f"\n[KPI 12] Top 10 produtos com menor rating:")
print(prod_rating.sort_values('avg_rating').head(10).to_string(index=False))

# ── KPI 13 – Produtos com maior número de reviews ───────────
top_reviews = (base_delivered.groupby('product_id')['review_score']
               .count()
               .reset_index()
               .rename(columns={'review_score': 'n_reviews'})
               .sort_values('n_reviews', ascending=False))
print(f"\n[KPI 13] Top 10 produtos com mais reviews:")
print(top_reviews.head(10).to_string(index=False))

# ── KPI 14 – Distribuição de ratings ────────────────────────
rating_dist = df_br_reviews['review_score'].value_counts().sort_index()
print(f"\n[KPI 14] Distribuição de ratings:")
print(rating_dist.to_string())

# ── KPI 15 – Correlação rating vs preço ─────────────────────
corr_rp = base_delivered[['review_score', 'price']].corr().iloc[0, 1]
print(f"\n[KPI 15] Correlação rating vs preço: {corr_rp:.4f}")

# ── KPI 16 – Correlação rating vs desconto ──────────────────
corr_rd = base_delivered[['review_score', 'discount_pct']].corr().iloc[0, 1]
print(f"[KPI 16] Correlação rating vs desconto: {corr_rd:.4f}")

# ── KPI 17 – Número total de produtos ───────────────────────
n_products = df_br_products['product_id'].nunique()
print(f"[KPI 17] Número total de produtos: {n_products:,}")

# ── KPI 18 – Número de categorias ───────────────────────────
n_categories = df_br_products['category'].nunique()
print(f"[KPI 18] Número de categorias: {n_categories}")

# ── KPI 19 – Produtos por categoria ─────────────────────────
prods_per_cat = (df_br_products.groupby('category')['product_id']
                 .count()
                 .sort_values(ascending=False)
                 .reset_index()
                 .rename(columns={'product_id': 'n_products'}))
print(f"\n[KPI 19] Produtos por categoria (top 10):")
print(prods_per_cat.head(10).to_string(index=False))

# ── KPI 20 – Categoria com maior número de produtos ─────────
top_cat = prods_per_cat.iloc[0]
print(f"\n[KPI 20] Categoria com mais produtos: {top_cat['category']} ({top_cat['n_products']} produtos)")

# ── KPI 21 – Produto mais caro ───────────────────────────────
prod_prices = df_br_items.groupby('product_id')['price'].max().reset_index()
mais_caro = prod_prices.sort_values('price', ascending=False).iloc[0]
print(f"\n[KPI 21] Produto mais caro:   ID {mais_caro['product_id']} — R$ {mais_caro['price']:.2f}")

# ── KPI 22 – Produto mais barato ────────────────────────────
mais_barato = prod_prices.sort_values('price').iloc[0]
print(f"[KPI 22] Produto mais barato: ID {mais_barato['product_id']} — R$ {mais_barato['price']:.2f}")

# ── KPI 23 – Produto mais avaliado (maior nº de reviews) ────
mais_avaliado = top_reviews.iloc[0]
print(f"\n[KPI 23] Produto mais avaliado: ID {mais_avaliado['product_id']} ({mais_avaliado['n_reviews']} reviews)")

# ── KPI 24 – Produto com melhor avaliação ───────────────────
melhor_avaliado = prod_rating.iloc[0]
print(f"[KPI 24] Produto com melhor avaliação: ID {melhor_avaliado['product_id']} (rating {melhor_avaliado['avg_rating']:.2f} ⭐)")

# ── KPI 25 – Reviews por categoria ──────────────────────────
reviews_per_cat = (base_delivered.groupby('category')['review_score']
                   .count()
                   .sort_values(ascending=False)
                   .reset_index()
                   .rename(columns={'review_score': 'n_reviews'}))
print(f"\n[KPI 25] Reviews por categoria (top 10):")
print(reviews_per_cat.head(10).to_string(index=False))

fig, axes = plt.subplots(4, 2, figsize=(18, 28))
fig.suptitle('KPIs — Dataset Olist', fontsize=18, fontweight='bold', y=1.01)
plt.subplots_adjust(hspace=0.55, wspace=0.35)

# ── Gráfico 1: KPI 2 — Preço médio por categoria (top 15) ───
ax = axes[0, 0]
top15 = avg_price_cat.head(15)
ax.barh(top15['category'][::-1], top15['avg_price'][::-1], color='steelblue')
ax.axvline(avg_price, color='tomato', linestyle='--', label=f'Média: R${avg_price:.0f}')
ax.set_title('[KPI 2] Preço Médio por Categoria (Top 15)')
ax.set_xlabel('Preço Médio (R$)')
ax.legend(fontsize=8)
ax.tick_params(axis='y', labelsize=7)

# ── Gráfico 2: KPI 4 — Distribuição de preços ───────────────
ax = axes[0, 1]
ax.hist(df_br_items['price'].clip(upper=1000), bins=50, color='steelblue', edgecolor='white')
ax.axvline(avg_price, color='tomato',  linestyle='--', label=f'Média: R${avg_price:.0f}')
ax.axvline(min_price, color='green',   linestyle='--', label=f'Mín: R${min_price:.0f}')
ax.axvline(max_price if max_price <= 1000 else 1000,
           color='orange', linestyle='--', label=f'Máx: R${max_price:.0f}')
ax.set_title('[KPI 1/3/4] Distribuição de Preços')
ax.set_xlabel('Preço (R$)')
ax.set_ylabel('Frequência')
ax.legend(fontsize=8)

# ── Gráfico 3: KPI 5/6 — Distribuição do desconto ───────────
ax = axes[1, 0]
disc_nonzero = base_delivered['discount_pct']
disc_nonzero = disc_nonzero[disc_nonzero > 0].clip(upper=30)
ax.hist(disc_nonzero, bins=40, color='mediumpurple', edgecolor='white')
ax.axvline(avg_disc_pct, color='tomato', linestyle='--',
           label=f'Média: {avg_disc_pct:.1f}%')
ax.set_title('[KPI 5/6] Distribuição do Desconto (%)')
ax.set_xlabel('Desconto (%)')
ax.set_ylabel('Frequência')
ax.legend(fontsize=8)

# ── Gráfico 4: KPI 14 — Distribuição de ratings ─────────────
ax = axes[1, 1]
cores = ['#e74c3c', '#e67e22', '#f1c40f', '#2ecc71', '#27ae60']
ax.bar(rating_dist.index, rating_dist.values, color=cores, edgecolor='white')
ax.set_title(f'[KPI 14] Distribuição de Ratings\nMédia: {avg_rating:.2f} ⭐')
ax.set_xlabel('Rating')
ax.set_ylabel('Nº de Avaliações')
ax.set_xticks([1, 2, 3, 4, 5])
for i, (xi, yi) in enumerate(zip(rating_dist.index, rating_dist.values)):
    ax.text(xi, yi + 300, f'{yi:,}', ha='center', fontsize=8)

# ── Gráfico 5: KPI 10 — Rating médio por categoria ──────────
ax = axes[2, 0]
top15_rat = avg_rating_cat.head(15)
cores_rat = ['#2ecc71' if v >= avg_rating else '#e74c3c' for v in top15_rat['avg_rating']]
ax.barh(top15_rat['category'][::-1], top15_rat['avg_rating'][::-1], color=cores_rat[::-1])
ax.axvline(avg_rating, color='gray', linestyle='--', label=f'Média: {avg_rating:.2f}')
ax.set_xlim(0, 5.5)
ax.set_title('[KPI 10] Rating Médio por Categoria (Top 15)')
ax.set_xlabel('Rating Médio')
ax.legend(fontsize=8)
ax.tick_params(axis='y', labelsize=7)

# ── Gráfico 6: KPI 15/16 — Correlação rating vs preço ───────
ax = axes[2, 1]
sample = base_delivered[['review_score', 'price']].dropna().sample(5000, random_state=42)
ax.scatter(sample['price'], sample['review_score'], alpha=0.15, s=8, color='steelblue')
z = np.polyfit(sample['price'], sample['review_score'], 1)
xline = np.linspace(0, sample['price'].quantile(0.95), 100)
ax.plot(xline, np.poly1d(z)(xline), color='tomato', linewidth=2,
        label=f'Tendência | r={corr_rp:.3f}')
ax.set_xlim(0, sample['price'].quantile(0.97))
ax.set_title('[KPI 15] Correlação Rating vs Preço')
ax.set_xlabel('Preço (R$)')
ax.set_ylabel('Rating')
ax.legend(fontsize=8)

# ── Gráfico 7: KPI 19/20 — Produtos por categoria (top 15) ──
ax = axes[3, 0]
top15_pc = prods_per_cat.head(15)
cores_pc = ['#e74c3c' if i == 0 else 'steelblue' for i in range(len(top15_pc))]
ax.bar(top15_pc['category'], top15_pc['n_products'], color=cores_pc, edgecolor='white')
ax.set_title(f'[KPI 19/20] Produtos por Categoria\nTotal: {n_products:,} produtos | {n_categories} categorias')
ax.set_xlabel('Categoria')
ax.set_ylabel('Nº de Produtos')
ax.tick_params(axis='x', rotation=45, labelsize=7)

# ── Gráfico 8: KPI 25 — Reviews por categoria (top 15) ──────
ax = axes[3, 1]
top15_rc = reviews_per_cat.head(15)
ax.bar(top15_rc['category'], top15_rc['n_reviews'], color='mediumpurple', edgecolor='white')
ax.set_title('[KPI 25] Reviews por Categoria (Top 15)')
ax.set_xlabel('Categoria')
ax.set_ylabel('Nº de Reviews')
ax.tick_params(axis='x', rotation=45, labelsize=7)

plt.tight_layout()
plt.savefig('kpis_olist.png', dpi=120, bbox_inches='tight')
plt.show()
print("Gráfico salvo como kpis_olist.png")

"""# Modelagem Preditiva, Algoritmos de Machine Learning e Métricas de Avaliação de Modelos"""

# base_delivered já foi criado no ETL anterior
df_olist_model = base_delivered[['price', 'freight_value', 'discount_pct', 'review_score']].dropna().copy()

X_ol = df_olist_model[['price', 'freight_value', 'discount_pct']]
y_ol = df_olist_model['review_score']

X_train, X_test, y_train, y_test = train_test_split(X_ol, y_ol, test_size=0.2, random_state=42)

modelo_olist = LinearRegression()
modelo_olist.fit(X_train, y_train)
y_pred_ol = modelo_olist.predict(X_test)

print(f"R²:   {r2_score(y_test, y_pred_ol):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_test, y_pred_ol)):.4f}")
print("Coeficientes:")
for feat, coef in zip(['price', 'freight_value', 'discount_pct'], modelo_olist.coef_):
    print(f"  {feat}: {coef:.6f}")

df_tree = base_delivered[['price', 'freight_value', 'discount_pct', 'review_score']].dropna().copy()
df_tree['review_alto'] = (df_tree['review_score'] >= 4).astype(int)

X_tree = df_tree[['price', 'freight_value', 'discount_pct']]
y_tree = df_tree['review_alto']

X_train, X_test, y_train, y_test = train_test_split(X_tree, y_tree, test_size=0.2, random_state=42)

arvore = DecisionTreeClassifier(max_depth=4, random_state=42)
arvore.fit(X_train, y_train)
y_pred_tree = arvore.predict(X_test)

print(f"Acurácia: {accuracy_score(y_test, y_pred_tree):.4f}")
print(classification_report(y_test, y_pred_tree, target_names=['Review Baixo', 'Review Alto']))

# Visualizar a árvore
plt.figure(figsize=(20, 8))
plot_tree(arvore, feature_names=['price', 'freight_value', 'discount_pct'],
          class_names=['Baixo', 'Alto'], filled=True, rounded=True, fontsize=9)
plt.title("Árvore de Decisão — Review Alto/Baixo (Olist)")
plt.tight_layout()
plt.show()

# Agregar métricas por vendedor
df_sellers_agg = (base_delivered
    .groupby('seller_id')
    .agg(
        receita_total=('price', 'sum'),
        n_pedidos=('order_id', 'nunique'),
        rating_medio=('review_score', 'mean'),
        preco_medio=('price', 'mean'),
        desconto_medio=('discount_pct', 'mean')
    )
    .dropna()
    .reset_index()
)

X_sell = StandardScaler().fit_transform(
    df_sellers_agg[['receita_total', 'n_pedidos', 'rating_medio', 'preco_medio']]
)

km_sell = KMeans(n_clusters=4, random_state=42, n_init=10)
df_sellers_agg['cluster'] = km_sell.fit_predict(X_sell)

print(df_sellers_agg.groupby('cluster').agg(
    receita_media=('receita_total', 'mean'),
    pedidos_medios=('n_pedidos', 'mean'),
    rating_medio=('rating_medio', 'mean'),
    n_vendedores=('seller_id', 'count')
).round(2))

plt.figure(figsize=(9, 6))
sns.scatterplot(data=df_sellers_agg, x='receita_total', y='rating_medio',
                hue='cluster', size='n_pedidos', palette='tab10',
                alpha=0.6, sizes=(30, 300))
plt.title("K-Means — Perfis de Vendedor (Olist)")
plt.xlabel("Receita Total (R$)")
plt.ylabel("Rating Médio")
plt.legend(title="Cluster", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

cm_tree = confusion_matrix(y_test, y_pred_tree)
disp_tree = ConfusionMatrixDisplay(confusion_matrix=cm_tree,
                                    display_labels=['Review Baixo', 'Review Alto'])
fig, ax = plt.subplots(figsize=(6, 5))
disp_tree.plot(ax=ax, colorbar=False, cmap='Greens')
plt.title("Matriz de Confusão — Árvore de Decisão (Olist)")
plt.tight_layout()
plt.show()